services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      node:
        condition: service_healthy
    restart: unless-stopped

  node:
    image: project-argus:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
            # ✅ 코드 자동 반영을 위한 bind mount 추가
      - .:/app
            # ✅ 업로드 데이터 폴더 연결
      - /app/node_modules
            # ✅ nodemon 감시 제외를 위한 옵션 가능 (선택)
      - /home/tslinux0101/uploads-data:/app/public/uploads
    env_file:
      - .env
            # ✅ nodemon 사용
    command: npm run dev
    depends_on:
      - mysql
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:5.7
    container_name: project-argus-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Tsrtmd@3300
      MYSQL_DATABASE: project_argus_db
    ports:
      - "3306:3306"
    volumes:
      - /home/tslinux0101/mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mysql_data:
