version: "3.9"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      node:
        condition: service_healthy
    restart: unless-stopped

  node:
    image: project-argus:dev # ✅ 이미지 이름 명시
    build:
      context: .
      dockerfile: Dockerfile.dev # ✅ 개발용 Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - /home/tslinux0101/uploads-data:/app/public/uploads # ✅ 절대 경로로 수정 : 운영시에는 상대경로로 지정해서 이식성을 증대시키는 것이 좋음
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5173" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:5.7
    container_name: project-argus-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Tsrtmd@3300
      MYSQL_DATABASE: project_argus_db
    ports:
      - "3306:3306"
    volumes:
      - /home/tslinux0101/mysql-data:/var/lib/mysql # 절대 경로로 변경해서 project 외부에서 관리리 ./mysql-data:/var/lib/mysql  # 상대경로 (이식성 증가)

  redis:
    image: redis:latest
    ports:
      - "6380:6380"

volumes:
  mysql_data:
